Repository rvolosatovs/turtlitto, pull requests merged in 2018-06, with the labels that each got.

#66 Switch to enzyme from react-renderer in tests
  front/src/Battery/__snapshots__/index.test.js.snap
  front/src/Battery/index.test.js
  front/src/Dropdown/__snapshots__/index.test.js.snap
  front/src/Dropdown/index.test.js
  front/src/NotificationWindow/__snapshots__/index.test.js.snap
  front/src/NotificationWindow/index.test.js
  front/src/RefboxField/RefboxButton.test.js
  front/src/RefboxField/__snapshots__/RefboxButton.test.js.snap
  front/src/RefboxField/__snapshots__/index.test.js.snap
  front/src/RefboxField/index.test.js
  front/src/RefboxSettings/ConfigDropdown.test.js
  front/src/RefboxSettings/DropBall.test.js
  front/src/RefboxSettings/InOutButton.test.js
  front/src/RefboxSettings/__snapshots__/ConfigDropdown.test.js.snap
  front/src/RefboxSettings/__snapshots__/DropBall.test.js.snap
  front/src/RefboxSettings/__snapshots__/InOutButton.test.js.snap
  front/src/RefboxSettings/__snapshots__/index.test.js.snap
  front/src/RefboxSettings/index.test.js
  front/src/Turtle/__snapshots__/index.test.js.snap
  front/src/Turtle/index.test.js
Labels: frontend

#67 front: Send turtle state changes to server
  front/src/Turtle/__snapshots__/index.test.js.snap
  front/src/Turtle/index.js
  front/src/Turtle/index.test.js
Labels: frontend

#56 front: Remove title NotificationWindow
  front/src/NotificationWindow/__snapshots__/index.test.js.snap
  front/src/NotificationWindow/index.js
  front/src/NotificationWindow/index.test.js
Labels: frontend

#76 front: Fix turtle state updates sent to TRC
  front/src/Turtle/__snapshots__/index.test.js.snap
  front/src/Turtle/index.js
Labels: frontend

#72 Add a refbox and add onclicks in app.js
  front/src/App.js
  front/src/RefboxField/RefboxButton.js
  front/src/RefboxField/__snapshots__/index.test.js.snap
  front/src/RefboxField/index.js
  front/src/RefboxSettings/DropBall.js
  front/src/RefboxSettings/__snapshots__/index.test.js.snap
  front/src/RefboxSettings/index.js
  front/src/Settings/index.test.js
  front/src/theme.js
Labels: frontend

#80 front: Fix typo in role names
  front/src/Turtle/index.js
Labels: bug, frontend

#79 front: Rename Turtle properties to follow specs
  front/src/App.js
  front/src/Turtle/index.js
  front/src/Turtle/index.test.js
Labels: frontend

#82 front: Fix notificationWindow
  front/src/NotificationWindow/__snapshots__/index.test.js.snap
  front/src/NotificationWindow/index.js
Labels: frontend

#75 Feature/backend auth
  pkg/api/api.go
  pkg/api/apitest/apitest.go
  pkg/trcapi/conn.go
  pkg/webapi/webapi.go
Labels: backend

#69 Mock TRC
  .travis.yml
  Makefile
  cmd/srrs/main.go
  cmd/srrs/main_test.go
  cmd/trcd/main.go
  cmd/trcd/main_unix.go
  cmd/trcd/main_windows.go
  pkg/trcapi/conn.go
Labels: backend

#85 front: Change turtle storage to be an object instead of an array
  front/package.json
  front/src/App.js
  front/src/Settings/__snapshots__/index.test.js.snap
  front/src/Settings/index.js
  front/src/Settings/index.test.js
  front/src/Turtle/index.js
  front/src/Turtle/index.test.js
  front/src/TurtleEnableBar/__snapshots__/index.test.js.snap
  front/src/TurtleEnableBar/index.js
  front/src/TurtleEnableBar/index.test.js
  front/yarn.lock
Labels: frontend

#94 front: Fail tests if console.error is called
  front/src/setupTests.js
Labels: enhancement, frontend

#89 Authorization and Logging
  Gopkg.lock
  cmd/srrs/main.go
  cmd/srrs/main_test.go
  cmd/trcd/main.go
  pkg/api/apitest/apitest.go
  pkg/trcapi/conn.go
  pkg/trcapi/conn_test.go
  pkg/trcapi/pool.go
  pkg/trcapi/trctest/trc.go
  pkg/webapi/webapi.go
Labels: backend, bug

#77 front: Add initial AuthenticationScreen
  front/src/App.js
  front/src/AuthenticationScreen/__snapshots__/index.test.js.snap
  front/src/AuthenticationScreen/index.js
  front/src/AuthenticationScreen/index.test.js
Labels: frontend, work-in-progress

#98 webapi: Fix authentication
  pkg/webapi/webapi.go
Labels: backend, bug

#83 front: Implement automatic reconnect
  front/src/App.js
  front/src/App.test.js
Labels: frontend

#97 front: Implement state receiving from SRRS
  front/src/App.js
  front/src/App.test.js
Labels: enhancement, frontend

#101 trcapi,srrs: Ping TRC connection every 5 seconds
  cmd/srrs/main.go
  pkg/trcapi/conn.go
Labels: backend

#103 front: Improve coverage of NotificationWindow
  front/src/NotificationWindow/index.test.js
Labels: frontend

#105 front: Only update turtles when actual turtles are sent
  front/src/App.js
  front/src/App.test.js
Labels: bug, frontend

#102 webapi: Add session support, encapsulate logic
  Gopkg.lock
  cmd/srrs/main.go
  cmd/srrs/main_test.go
  pkg/api/api.go
  pkg/api/apitest/apitest.go
  pkg/api/validate.go
  pkg/api/validate_test.go
  pkg/logcontext/context.go
  pkg/trcapi/conn.go
  pkg/trcapi/conn_test.go
  pkg/trcapi/trctest/trc.go
  pkg/webapi/webapi.go
Labels: backend

#106 front: Add ConnectionBar AuthenticationScreen
  front/src/App.js
  front/src/AuthenticationScreen/__snapshots__/index.test.js.snap
  front/src/AuthenticationScreen/index.js
  front/src/AuthenticationScreen/index.test.js
Labels: frontend

#109 coverage: Enable partial line coverage for javascript
  .codecov.yml
Labels: frontend

#111 front: Add grid to turtle list
  front/src/TurtleList/__snapshots__/index.test.js.snap
  front/src/TurtleList/index.js
Labels: bug, frontend

#110 Add support for auth-less builds
  Makefile
  pkg/trcapi/conn.go
  pkg/trcapi/token_auth.go
  pkg/trcapi/token_noauth.go
  pkg/webapi/webapi.go
Labels: backend

#116 front: Fix editorconfig violation
  front/src/App.js
Labels: frontend

#112 front: Implement authentication further, most notably Websockets.
  front/src/App.js
  front/src/App.test.js
  front/src/AuthenticationScreen/__snapshots__/index.test.js.snap
  front/src/AuthenticationScreen/index.js
  front/src/AuthenticationScreen/index.test.js
  front/src/BottomBar/__snapshots__/index.test.js.snap
  front/src/BottomBar/index.js
  front/src/RefboxField/__snapshots__/index.test.js.snap
  front/src/RefboxField/index.js
  front/src/RefboxSettings/__snapshots__/DropBall.test.js.snap
  front/src/RefboxSettings/__snapshots__/InOutButton.test.js.snap
  front/src/RefboxSettings/index.js
  front/src/Settings/__snapshots__/index.test.js.snap
  front/src/Settings/index.js
  front/src/Turtle/__snapshots__/index.test.js.snap
  front/src/Turtle/index.js
  front/src/Turtle/index.test.js
  front/src/TurtleList/index.js
  front/src/sendToServer.js
Labels: frontend

#115 front: Receive current command from server
  front/src/App.js
  front/src/Settings/__snapshots__/index.test.js.snap
  front/src/Settings/index.js
  front/src/Settings/index.test.js
Labels: enhancement, frontend

#114 Webapi: Make compliant with SRD
  pkg/trcapi/conn.go
  pkg/trcapi/trctest/trc.go
  pkg/webapi/webapi.go
Labels: backend

#122 front: Translate between display and protocol name in Turtle
  front/src/Settings/__snapshots__/index.test.js.snap
  front/src/Settings/index.test.js
  front/src/Turtle/__snapshots__/index.test.js.snap
  front/src/Turtle/index.js
  front/src/Turtle/index.test.js
  front/src/TurtleList/__snapshots__/index.test.js.snap
  front/src/TurtleList/index.test.js
Labels: bug, frontend

#125 front: Move command dropdown under the turtle list
  front/src/Settings/__snapshots__/index.test.js.snap
  front/src/Settings/index.js
Labels: frontend

#126 api,trcapi: hardcode the 6 turtles
  cmd/trcd/main.go
  pkg/api/apitest/apitest.go
  pkg/api/validate.go
  pkg/trcapi/conn.go
  pkg/trcapi/conn_test.go
Labels: backend

#132 front: Add mobile-web-app-capable meta element
  front/public/index.html
Labels: enhancement, frontend

#134 front: Don't display notificationwindows
  front/src/App.js
Labels: frontend

#133 webapi,srrs: Only connect to TRC when SRRC active
  Makefile
  cmd/srrs/main.go
  cmd/srrs/main_test.go
  cmd/trcd/main.go
  pkg/webapi/webapi.go
Labels: backend, bug

#136 front: Move refbox to top
  front/src/App.js
  front/src/RefboxSettings/__snapshots__/index.test.js.snap
  front/src/RefboxSettings/index.js
Labels: enhancement, frontend

#137 front: Add support bar to some browsers
  front/src/App.js
  front/src/SupportBar.js
Labels: bug, frontend
